### ISSUE TITLE
Getting an error with pop_os 19.10

### ISSUE THREAD

**Issue by kprojects** [withinboredom/system-76-keyboards#2]
Hey there,

I'm getting an error with ubuntu/pop 19.10 and wondering if you've tried it with this version.. once it starts up, i'm seeing:

PHP Warning:  file_put_contents(/sys/class/leds/system76::kbd_backlight/color_center): failed to open stream: No such file or directory in /opt/keyboard-colors/keyboard-color.php on line 374

Wondering if you've seen this before or have any suggestions?

**Comment by kprojects** [comment]
I was able to somewhat fix this by changing some paths in the keyboard-color.php script with
`/sys/class/leds/system76_acpi::kbd_backlight/color`
when referring to the backlight directory.. I have coreboot and thinking this was one of the changes.. also seems like there used to be color_left, color_center and color_right in the past so it'd flow from left to right ..

**Comment by withinboredom** [comment]
In a more recent firmware update, access to the leds was disabled on my machine. So sadly, I haven't been able to use the script since then :)

Glad you got it working somewhat though!

**Comment by withinboredom** [comment]
I've rewritten this in C# and it should now handle missing parts of the keyboard. If it doesn't, reopen this issue.
