### ISSUE TITLE
Support for keyboards with only one color zone

### ISSUE THREAD

**Issue by thesquaregroot** [withinboredom/system-76-keyboards#4]
I found that this project doesn't work on my Darter Pro due to the fact the only backlight-color file available is `/sys/class/leds/system76_acpi::kbd_backlight/color` (i.e. no left/center/right, only "color" for the whole keyboard).  Doing a grep on the project I'm pretty sure this isn't referenced anywhere.

It seems like this was the core issue with #2 (since they referenced this path as somewhat fixing their issue) but since they were using the PHP version I figured it might make sense to post this as a separate issue.

**Comment by withinboredom** [comment]
Try [this release — 1.0.2](https://github.com/withinboredom/system-76-keyboards/releases/tag/1.0.2)

**Comment by thesquaregroot** [comment]
That definitely got it working when trying it out directly I ran into some problems.  The contents of the service file were:

```
[Unit]
Description=System76 Keyboard Colors
[Service]
Type=Simple
ExecStart=/usr/local/bin/keyboard-color monitor --service --service
PIDFile=keyboard-colors.pid
[Install]
WantedBy=multi-user.target
```

With which I got the error (via `systemctl status keyboard-colors`):

```
Warning: The unit file, source configuration file or drop-ins of keyboard-colors.service changed on disk. Run 'systemctl daemon-reload' to reload units.
keyboard-colors.service - System76 Keyboard Colors
   Loaded: loaded (/etc/systemd/system/keyboard-colors.service; enabled; vendor preset: enabled)
   Active: failed (Result: core-dump) since Sun 2019-11-24 18:36:23 EST; 41s ago
  Process: 2612 ExecStart=/usr/local/bin/keyboard-color monitor --service (code=dumped, signal=ABRT)
 Main PID: 2612 (code=dumped, signal=ABRT)

Nov 24 18:36:23 pop-os keyboard-color[2612]: Unhandled exception. System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
Nov 24 18:36:23 pop-os keyboard-color[2612]:    at System.ConsolePal.ReadKey(Boolean intercept)
Nov 24 18:36:23 pop-os keyboard-color[2612]:    at System.Console.ReadKey(Boolean intercept)
Nov 24 18:36:23 pop-os keyboard-color[2612]:    at keyboards.Installer.CreateService()
Nov 24 18:36:23 pop-os keyboard-color[2612]:    at keyboards.Program.RunOrInstall(String[] args, Options options, Keyboard kb)
Nov 24 18:36:23 pop-os keyboard-color[2612]:    at keyboards.Program.<>c__DisplayClass9_0.<Main>b__2(MonitorOptions o)
Nov 24 18:36:23 pop-os keyboard-color[2612]:    at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 notParsedFunc)
Nov 24 18:36:23 pop-os keyboard-color[2612]:    at keyboards.Program.Main(String[] args)
Nov 24 18:36:23 pop-os systemd[1]: keyboard-colors.service: Main process exited, code=dumped, status=6/ABRT
Nov 24 18:36:23 pop-os systemd[1]: keyboard-colors.service: Failed with result 'core-dump'.
```

After running `systemctl daemon-reload`, it just tacked on:

> /etc/systemd/system/keyboard-colors.service:4: Failed to parse service type, ignoring: Simple

After that I tried changing the service type to "simple" (lower case s) and got:

```
Nov 24 18:40:02 pop-os keyboard-color[2734]: Copyright (C) 2019 withinboredom (Rob Landers)
Nov 24 18:40:02 pop-os keyboard-color[2734]: ERROR(S):
Nov 24 18:40:02 pop-os keyboard-color[2734]:   Option 's, service' is defined multiple times.
Nov 24 18:40:02 pop-os keyboard-color[2734]:   -f, --filter       Specify a filter to use
Nov 24 18:40:02 pop-os keyboard-color[2734]:   -h, --frequency    (Default: 0.25) Determine the delay between frames
Nov 24 18:40:02 pop-os keyboard-color[2734]:   -i, --install      Install the active command
Nov 24 18:40:02 pop-os keyboard-color[2734]:   --help             Display this help screen.
Nov 24 18:40:02 pop-os keyboard-color[2734]:   --version          Display version information.
Nov 24 18:40:02 pop-os systemd[1]: keyboard-colors.service: Main process exited, code=exited, status=1/FAILURE
Nov 24 18:40:02 pop-os systemd[1]: keyboard-colors.service: Failed with result 'exit-code'.
```

I then tried removing the second `--service` argument which basically got me back to the beginning and even overwrote my changes to the service file.

Any thoughts?

**Comment by withinboredom** [comment]
Did you run with `--install --service`? Try your install command without `--service`, but make sure you've terminated any other running instances. `--service` is only supposed to be used in the systemd service file (but should probably be the default behavior).

**Comment by withinboredom** [comment]
Try this beta, which is quite a bit more resilient and should work better: https://github.com/withinboredom/system-76-keyboards/releases/tag/1.1.0-beta.0

**Comment by thesquaregroot** [comment]
It's installing and running much better.

I did run into an issue with the monitor setting (which I really like the idea of).  I was doing some testing just to see how it responded to different levels of load and found that once I crossed about 75% CPU usage, the service dies and my keyboard stays yellow.  If I restart the service it works fine until I hit that level of load again when it dies again.  The service status isn't very helpful though:

```
keyboard-colors.service - System76 Keyboard Colors
   Loaded: loaded (/etc/systemd/system/keyboard-colors.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-11-25 08:45:06 EST; 1s ago
  Process: 4726 ExecStart=/usr/local/bin/keyboard-color monitor (code=exited, status=1/FAILURE)
 Main PID: 4726 (code=exited, status=1/FAILURE)

Nov 25 08:44:05 pop-os systemd[1]: Started System76 Keyboard Colors.
Nov 25 08:45:06 pop-os systemd[1]: keyboard-colors.service: Main process exited, code=exited, status=1/FAILURE
Nov 25 08:45:06 pop-os systemd[1]: keyboard-colors.service: Failed with result 'exit-code'.
```

I was testing using the tool stress using the command `stress --cpu 6`, and my laptop supports up to 8 threads with hyper-threading.  Anything above 75% seems to kill it but it works well below that (i.e. with 5 threads or fewer).

All of that said, I'm guessing this is probably a different issue than the initial one so if you'd rather I close this one and open a new issue I can do that, just let me know.

**Comment by withinboredom** [comment]
Oh nice, I'm seeing that too! I'll open an issue. It only happens with the release version and not the debug version, so likely related to an optimization being made there: `Arithmetic operation resulted in an overflow.`

**Comment by withinboredom** [comment]
https://github.com/withinboredom/system-76-keyboards/releases/tag/1.1.0-beta.1

There's a fix for now :)

**Comment by thesquaregroot** [comment]
Everything seems to be working well now.  Thanks!
